# Generated by Django 5.0.1 on 2024-02-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default='perfil/default.jpg', upload_to='perfil/'),
        ),
    ]
